GET http://localhost:3000/profiles?location=nyc   

### 
GET http://localhost:3000/profiles/08c4ee1f-e1f5-44e0-b1e8-874eaba1b930

### 
POST http://localhost:3000/profiles
Content-Type: application/json

{
    "name": "John Doe",
    "description": "A sample profile"
}

###
PUT http://localhost:3000/profiles/08c4ee1f-e1f5-44e0-b1e8-874eaba1b930
Content-Type: application/json

{
    "name": "John Doe u",
    "description": "A sample pofile u"
}

###
DELETE http://localhost:3000/profiles/2e645643-ee91-4b90-a3fb-149ffd64f0e3