GET http://localhost:3000/profiles?location=nyc   

### 
GET http://localhost:3000/profiles/4948488a-7d1f-4ea8-a8ce-8f0f7b8df4db

### 
POST http://localhost:3000/profiles
Content-Type: application/json

{
    "name": "John Doe",
    "description": "A sample profile"
}

###
PUT http://localhost:3000/profiles/08c4ee1f-e1f5-44e0-b1e8-874eaba1b930
Content-Type: application/json

{
    "name": "John Doe u",
    "description": "A sample pofile u"
}

###
DELETE http://localhost:3000/profiles/312baa7f-65be-43f6-9bf9-14f6c23bb8e1